version: '3'

services:
  nginx:
    image: 127.0.0.1:5000/uclapi_nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    links:
      - django

  django:
    image: 127.0.0.1:5000/uclapi_django
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
        environment: prod
    ports:
      - "9000:9000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
