version: '3'

services:
  web:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    env_file: ./backend/uclapi/.env
    environment: 
        DOCKER: "yes"
        DOCKER_DEPLOYMENT: "prod"
        PYTHONUNBUFFERED: 0
